### ISSUE TITLE
Real-world demo video

### ISSUE THREAD

**Issue by SteveMacenski** [open-navigation/opennav_coverage#19]

**Comment by yishaiSilver** [comment]
Hi Steve, did you still want a real-world demo video?

This is a simple differential robot that I built with hoverboard wheels.

https://github.com/user-attachments/assets/e44d8f10-c5b0-4345-81ad-25f3bcd06030

**Comment by SteveMacenski** [comment]
@yishaiSilver thank you! I added it to our readme :-)

**Comment by yishaiSilver** [comment]
@SteveMacenski Awesome! I'm so glad to contribute to such an amazing project, even in a very small way.
