### ISSUE TITLE
no visualisation on rviz

### ISSUE THREAD

**Issue by NK1807** [open-navigation/opennav_coverage#38]
firstly, I appreciate the efforts put into this amazing package.

@SteveMacenski , I'm trying out the demos and encountered that the topics from /coverage_server/XXX  has no data when echoed. rviz is also unable to visualize the filed boundary, swaths etc. But, the robot is being navigated as shown in the demo videos.

![Screenshot from 2024-01-03 13-33-48](https://github.com/open-navigation/opennav_coverage/assets/29913941/d7b28748-cae1-4550-865c-01143a8e70b6)
working environment:
Ubuntu 22.04
ROS Humble

Am I missing some steps?

**Comment by SteveMacenski** [comment]
Are you using the right global frame w.r.t. your data frame so that the data is visualizable? If you echo the topics that are to be visualized, what frame are they in?

**Comment by NK1807** [comment]
Thanks for the comment.
True, the robot is navigating properly as shown in the demos and the echo should work but 
global frame is already set to map frame. Fyi, I didn't make any changes to the existing demo code ( https://github.com/open-navigation/opennav_coverage/blob/main/opennav_coverage_demo/launch/coverage_demo_launch.py ). I'm just trying to launch the two exisiting demos( coverage and row_coverage). I have just it with ROS Iron on another system too but the same issue. 
Could you please share if there is some documentation on demos? or is it just launching coverage_demo_launch.py / row_coverage_demo_launch.py?

**Comment by SteveMacenski** [comment]
I had tested this on release about a week before the holidays working fine. Are you sure you have the rviz topics set to visualize at all and set at launch time before the robot starts moving? It only publishes once at planning time. The default rviz config you're using may not have the coverage topics in the display panel.

**Comment by NK1807** [comment]
Yes, It worked now. I saved the rviz config and launched it before starting the demo.
Thanks! @SteveMacenski :)
