### ISSUE TITLE
Coverage Path and polygons only published once

### ISSUE THREAD

**Issue by Myzhar** [open-navigation/opennav_coverage#39]
I noticed that the coverage path is published only once after it is generated, and the message is no more available for subscribers to its topic created after the publication.

For example, with the demos, RVIZ cannot display the path if it's launched after a demo is started.

**Comment by SteveMacenski** [comment]
This is an action server to compute the coverage paths, that publication is purely for debugging. Use the action client to obtain the coverage path from calling the server.
