### ISSUE TITLE
Coverage Demo fails

### ISSUE THREAD

**Issue by tonynajjar** [open-navigation/opennav_coverage#41]
How to reproduce:

`ros2 launch opennav_coverage_demo coverage_demo_launch.py`

Error:

`[component_container_isolated-5] [ERROR] [1709560390.632574795] [coverage_server]: Internal Fields2Cover error: Geometry does not contain point 0`

**Comment by SteveMacenski** [comment]
You need to populate your field correctly - see the demo script or the tests (or even other F2C demos)

**Comment by tonynajjar** [comment]
You're saying that it is expected that running the demo launch file should not work out of the box? I saw that in the demo script `demo_coverage.py`, a polygon is generated and I'm guessing in the `coverage_server` this polygon is converted to the master_field, yet this master_field seems to have an area of 0. What am I missing here?

**Comment by tonynajjar** [comment]
In `computeCoveragePath`, I printed out the goal and it seems to be populated correctly (same as in the `demo_coverage` script). Then I printed out `master_field.getArea()` and that's 0. There seems to be something wrong in the creation of the master_field from the polygon.

**Comment by SteveMacenski** [comment]
Sorry, took me a bit to get a workspace built with everything. It seems to be working fine for me on `iron`

```
git clone git@github.com:Fields2Cover/Fields2Cover.git
git clone git@github.com:open-navigation/opennav_coverage.git
colcon build --packages-select opennav_coverage opennav_coverage_demo opennav_coverage_msgs fields2cover

ros2 launch opennav_coverage_demo coverage_demo_launch.py
```

**Comment by tonynajjar** [comment]
Hmm, I tested on main, could you give this a quick test? I probably won't have time today anymore to test on Iron, I can try it tommorrow.

**Comment by SteveMacenski** [comment]
Works fine too. 

```
[demo_coverage-7] Waiting for 'NavigateCompleteCoverage' action server
[demo_coverage-7] Navigating to with field of size: 5...
[component_container_isolated-5] [INFO] [1709574892.421465036] [bt_navigator]: Begin coverage navigating with outer field of size: 5!
[component_container_isolated-5] [INFO] [1709574892.425943049] [coverage_server]: Generating coverage path in map frame for zone with 5 outer nodes and 0 inner polygons.
[component_container_isolated-5] [INFO] [1709574892.455748830] [controller_server]: Received a goal, begin computing control effort.
```

**Comment by tonynajjar** [comment]
Well, thank you for taking the time.... I'll check tomorrow how that could happen...

**Comment by tonynajjar** [comment]
Are you sure you tested with navigation2 and opennav_coverage on main? How did you not run into https://github.com/open-navigation/opennav_coverage/pull/43?
