### ISSUE TITLE
amcl_pose option next to GPS coordinates

### ISSUE THREAD

**Issue by berkettunckal** [open-navigation/opennav_coverage#45]
The Fields2Cover package works with GPS, and the open_nav_coverage package I think is an adaptation with navigation. Do you plan to integrate with amcl_pose or odom in the future?

**Comment by SteveMacenski** [comment]
Fields2Cover can take any type of input polygon data, including cartesian, today! You can see that in the demo package, we define a cartesian map framed field that is used to generate the path and the robot is routed along that path in map frame. 

Done!

**Comment by berkettunckal** [comment]
Thank you!
