### ISSUE TITLE
Not considering holes when path planning

### ISSUE THREAD

**Issue by muscle-lee** [open-navigation/opennav_coverage#50]
![Screenshot from 2024-01-11 10-44-17](https://github.com/open-navigation/opennav_coverage/assets/161572690/66213b78-b17e-49d7-858d-831ad72d46c7)

It considers holes when making swath but, it ignores holes on the step of making route and path.
I think, to solve this problem decomposition part should be added. But it's not in Field2Cover.
Do you have any plan to improve when merging to nav2?

**Comment by SteveMacenski** [comment]
That is not currently a supported feature and won’t be until F2C itself supports it. This is a flexible wrapper for it.
