### ISSUE TITLE
Unable to build humble

### ISSUE THREAD

**Issue by yishaiSilver** [open-navigation/opennav_coverage#55]
Hello, as the title suggests, I am unable to build the humble branch using the same methodology as the [comment listed here](https://github.com/open-navigation/opennav_coverage/issues/41#issuecomment-1977121442). Fields2Cover will build, but opennav_coverage will not.

The error is mostly a repeat of:
```
/home/ssilver/coverage/opennav_coverage/opennav_coverage/include/opennav_coverage/utils.hpp:182:14: error: ‘opennav_coverage::Path’ {aka ‘struct f2c::types::Path’} has no member named ‘states’; did you mean ‘std::vector<f2c::types::PathState> f2c::types::Path::states_’? (not accessible from this context)

  182 |     if (path.states[i].type != PathSectionType::SWATH &&

      |              ^~~~~~
```
 
 I have also seen similar issues for a few other variables. Please let me know if I should post colcon's output in its entirety. 

Anyways, thank you for the amazing work (on this package and on nav2 as a whole). Any help is appreciated.

**Comment by SteveMacenski** [comment]
This package currently targets F2C v1, if you’re pulling from main in F2C, that is v2 which an open PR #53 aims to add support for

**Comment by yishaiSilver** [comment]
Okay, thank you. I didn't see any branches on F2C, but I finally found v1 [here](https://github.com/Fields2Cover/Fields2Cover/releases/tag/v1.2.1). That PR makes more sense now.
