### ISSUE TITLE
ROS2 Humble: Failed to build

### ISSUE THREAD

**Issue by grboguz21** [open-navigation/opennav_coverage#58]
Hi, 
I'm using **_Ubuntu 22.04_** and _**ROS2 Humble**_. I'm following the steps below but can't build the humble branch:
```
git clone https://github.com/Fields2Cover/Fields2Cover.git
git clone https://github.com/open-navigation/opennav_coverage.git -b humble
colcon build --packages-select opennav_coverage opennav_coverage_demo opennav_coverage_msgs fields2cover

ros2 launch opennav_coverage_demo coverage_demo_launch.py
```

When I build the packages as above, I'm getting lots of error. The last part of the error is something like this:
```
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:90: CMakeFiles/opennav_coverage_core.dir/src/headland_generator.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:118: CMakeFiles/opennav_coverage_core.dir/src/route_generator.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:104: CMakeFiles/opennav_coverage_core.dir/src/swath_generator.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:146: CMakeFiles/opennav_coverage_core.dir/src/visualizer.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:132: CMakeFiles/opennav_coverage_core.dir/src/path_generator.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:76: CMakeFiles/opennav_coverage_core.dir/src/coverage_server.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:188: CMakeFiles/opennav_coverage_core.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< opennav_coverage [13.1s, exited with code 2]

Summary: 2 packages finished [1min 8s]
  1 package failed: opennav_coverage
  2 packages had stderr output: fields2cover opennav_coverage
  1 package not processed
```

Error Message (whole message):

![Screenshot from 2024-05-24 21-16-26](https://github.com/open-navigation/opennav_coverage/assets/170757002/f7b04247-05f6-45f4-854c-a707ac799528)

Thanks for your time !

**Comment by grboguz21** [comment]
I replaced fields2cover package to v1.2.0 which is in this link: https://github.com/Fields2Cover/Fields2Cover/releases/tag/v1.2.0
but interestingly still getting same error:
```
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:90: CMakeFiles/opennav_coverage_core.dir/src/headland_generator.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:132: CMakeFiles/opennav_coverage_core.dir/src/path_generator.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:76: CMakeFiles/opennav_coverage_core.dir/src/coverage_server.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/opennav_coverage_core.dir/build.make:146: CMakeFiles/opennav_coverage_core.dir/src/visualizer.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:188: CMakeFiles/opennav_coverage_core.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< opennav_coverage [16.1s, exited with code 2]
Aborted  <<< Fields2Cover [1min 5s]                                        

Summary: 1 package finished [1min 5s]
  1 package failed: opennav_coverage
  1 package aborted: Fields2Cover
  2 packages had stderr output: Fields2Cover opennav_coverage
  1 package not processed
```

Error Message (whole message):
![Screenshot from 2024-05-25 17-09-38](https://github.com/open-navigation/opennav_coverage/assets/170757002/e2717fb9-2815-4497-a5a9-5082c824f5dd)

**Comment by datnguyen2803** [comment]
Hi @grboguz21 ,
I faced the same issue and you need **v1.2.1**.

**Comment by grboguz21** [comment]
I tried your method but unfortunately getting the almost same error message.. 
In order to help to find stabil installation process at least Humble users, I want to share my whole steps:

**_First of all_**, I created folders listed below:
```
cd ~
mkdir open_navigation_ws
mkdir open_navigation_ws/src
cd open_navigation_ws/src
```
 
**_and after that_** I downloaded packages using a bunch of commands below:
```
git clone https://github.com/Fields2Cover/Fields2Cover.git -b v1.2.1
git clone https://github.com/open-navigation/opennav_coverage.git -b humble
```

_**Finally**_, I got back to the main project folder and build the workspace:
```
cd ~/open_navigation_ws
colcon build --packages-select opennav_coverage opennav_coverage_demo opennav_coverage_msgs fields2cover
```

**_After building that_**, getting errors related to **_swath_generator.cpp_** and _**coverage_server.cpp**_:
![Screenshot from 2024-05-27 09-13-21](https://github.com/open-navigation/opennav_coverage/assets/170757002/d715eead-46ac-4dcc-bab0-cf11aba137da)

Something interestingly was getting wrong.

**Comment by datnguyen2803** [comment]
Hi @grboguz21 ,
After cloning F2C v1.2.1, shouldn't you build and install that library first? I follow the guideline in [F2C repo](https://github.com/Fields2Cover/Fields2Cover). 
![image](https://github.com/open-navigation/opennav_coverage/assets/50166306/3708a3d9-5483-4cf7-bf0f-69484a70240c)
After that, "colcon build" opennav_coverage source

**Comment by grboguz21** [comment]
**_First of all, thank you for your time._**

I missed the point that install building and installing library.
As you said, I deleted all files related directories in **_/usr_** or _**/opt**_.

After that, I got back to the main folder of _**Fields2Cover**_ package which is `~/open_navigation_ws/src/Fields2Cover`.
In this directory, I ran these commands:
```
mkdir -p build;
cd build;
cmake -DCMAKE_BUILD_TYPE=Release ..;
make -j$(nproc);
sudo make install;
```

After that, I wanted to test this library in _**Python**_ first. In order to do that, I ran these commands below:
![Screenshot from 2024-05-28 09-38-08](https://github.com/open-navigation/opennav_coverage/assets/170757002/903fcf9f-30b5-437b-8543-24216ea6be53)

Everything was fine so far. As you see library is successfully installed:
![Screenshot from 2024-05-28 09-46-26](https://github.com/open-navigation/opennav_coverage/assets/170757002/c7129e67-d8a0-4bcd-928e-cea63c1241fe)

But when I try to build with `colcon` it failed:
![Screenshot from 2024-05-28 09-47-02](https://github.com/open-navigation/opennav_coverage/assets/170757002/25195c06-2002-4da5-88b6-f2aaed42df24)

**Comment by grboguz21** [comment]
I would like to thank to everyone for helping me.
I tried your steps @emusman-lab and attached the log message below as **_.txt_** file. 
[output.txt](https://github.com/open-navigation/opennav_coverage/files/15478915/output.txt)

and also screenshot of the error message:
![Screenshot from 2024-05-29 07-55-48](https://github.com/open-navigation/opennav_coverage/assets/170757002/b4fe30ee-fa3c-4f72-8946-8fcf503c86f0)

**Comment by grboguz21** [comment]
**_I finally solved it !_**
Your kind support save my life @emusman-lab, I would like to special thank to you. 

![Screenshot from 2024-05-29 08-23-42](https://github.com/open-navigation/opennav_coverage/assets/170757002/6c2bb3c8-3186-46fd-b0c8-3e753bd2eca2)

Now, I'm going to create a clear installation process of your awesome package for **_ROS2 Humble_** users and share here @SteveMacenski if you are considering using it for people looking for a solution.

I hope this will be helpful for everyone who are interested in this package.

**Comment by MarcM0** [comment]
I have the same error on iron,
here are the steps I used
`
source /opt/ros/iron/setup.bash
cd ~
mkdir open_navigation_ws
mkdir open_navigation_ws/src
cd open_navigation_ws/src
git clone https://github.com/Fields2Cover/Fields2Cover.git -b v1.2.1
git clone https://github.com/open-navigation/opennav_coverage.git -b iron

cd ~/open_navigation_ws/src/Fields2Cover
git checkout tags/v1.2.1
mkdir -p build; 
cd build; cmake -DCMAKE_BUILD_TYPE=Release ..; 
make -j$(nproc); 
sudo make install;

source /opt/ros/iron/setup.bash
cd ~/open_navigation_ws/src/Fields2Cover
colcon build --symlink-install
cd ~/open_navigation_ws/src/opennav_coverage/
colcon build --symlink-install
source install/setup.bash
ros2 launch opennav_coverage_demo coverage_demo_launch.py
`

**Comment by MarcM0** [comment]
Nevermind, I fixed it by removing anything related to fields2cover from my pc before reinstalling

**Comment by SteveMacenski** [comment]
Closing, since [this ticket](https://github.com/open-navigation/opennav_coverage/issues/56) covers that need to update the instructions since F2C v2.0 is API breaking, but thanks for the thread folks! https://github.com/open-navigation/opennav_coverage/issues/56

**Comment by JaMan-cmd** [comment]
I cloned F2C , version 2.0, built it, tried to build opennav_coverage with no luck. I was happy to find this thread, so I deleted F2C, erased all related folders in /usr and cloned V1.2, built it, then while building opennav_coverage, I got the following error
`--- stderr: opennav_coverage                                     
/usr/bin/ld: CMakeFiles/test_viz.dir/test_viz.cpp.o: undefined reference to symbol '_ZNK11OGRGeometry11exportToWktEPPc13OGRwkbVariant'
/usr/bin/ld: /lib/libgdal.so.30: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
`
