### ISSUE TITLE
Simple Commander API Breaks

### ISSUE THREAD

**Issue by yishaiSilver** [open-navigation/opennav_coverage#62]
Hello,

In the past I have been able to successfully use Nav2's Simple Commander API, but I get the following error after having included this package (I'm hoping to use both):

```
[ERROR] [bt_navigator-9]: process has died [pid 139, exit code 127, cmd '/opt/ros/humble/lib/nav2_bt_navigator/bt_navigator --ros-args --log-level info --ros-args -r __node:=bt_navigator --params-file /tmp/launch_params_9176n68w -r /tf:=tf -r /tf_static:=tf_static'].
[bt_navigator-9] /opt/ros/humble/lib/nav2_bt_navigator/bt_navigator: symbol lookup error: /opt/ros/humble/lib/nav2_bt_navigator/bt_navigator: undefined symbol: _ZN17nav2_bt_navigator11BtNavigatorC1EN6rclcpp11NodeOptionsE
```

My binaries are:
```
Package: ros-humble-navigation2
Version: 1.1.14-1jammy.20240518.070250
```
And I am using the latest commit of opennav_coverage on the humble branch.

I can confirm that the error does not appear after removing this package and then rebuilding (and launching in the exact same way). Likewise, I can successfully execute the coverage task, so I suspect there is some cross-compatibility issue. 

I understand that the humble branch has a backported_bt_navigator, but I'm somewhat of a novice at C++ and I'm not quite sure why it wouldn't work with the existing packages. In fact, I tried changing the CMakeLists.txt to install the behavior_trees:  `install(DIRECTORY behavior_trees DESTINATION share/${PROJECT_NAME})` (as well as copying that directory to the backported_bt_navigator directory). It compiled, but the error still occurs. Otherwise I haven't touched anything as I'm not very comfortable with C++.

Any help would be appreciated.

**Comment by SteveMacenski** [comment]
Try apt update, apt upgrade, purging the binaries, and reinstalling. Could just be that you’re out of sync with some core libraries.

**Comment by yishaiSilver** [comment]
Okay, I believe I did those correctly by updating my Dockerfile as follows:

```
RUN apt update && apt upgrade -y && apt dist-upgrade -y

RUN apt purge -y \
        ...
	ros-${ROS_DISTRO}-navigation2 \
        ros-${ROS_DISTRO}-nav2-bringup \
	...
	&& \
    rm -rf /var/lib/apt/lists/*

RUN apt update && \
        apt install -y --reinstall \
        ...
	ros-${ROS_DISTRO}-navigation2 \
        ros-${ROS_DISTRO}-nav2-bringup \
	...
	&& \
    rm -rf /var/lib/apt/lists/*
```
Unfortunately, though. I'm still getting the error above. In the meanwhile, I can try it with Iron and report those results.

**Comment by SteveMacenski** [comment]
I'm currently working on a project with Humble binaries doing some basic navigation and not running into this issue, I'm pretty sure its to do with your setup and something not being up-to-date. 

I think we should close unless you have more you can add to this or someone else reports a similar issue (I imagine if the Humble binaries are broken, we'd be seeing alot of reports!). I'd recommend updating your docker image with a pull and trying with a fresh re-build after deleting your install/build/log directories. Sometimes caches after apt updates can make things wacky.

**Comment by yishaiSilver** [comment]
Okay, I'll try that and give an update. Other than that I don't have anything to add, but thank you for your help (and all the amazing work)!
