### ISSUE TITLE
Colcon build Error

### ISSUE THREAD

**Issue by RamanaBotta** [open-navigation/opennav_coverage#63]
**System Details**:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
**ROS2 version** :  Humble 
**Branch** : humble (https://github.com/open-navigation/opennav_coverage/tree/humble)

**colcon build Error:**
```

Starting >>> opennav_coverage_msgs
Starting >>> backported_bt_navigator
Finished <<< backported_bt_navigator [0.28s]                                                                        
Finished <<< opennav_coverage_msgs [1.91s]                     
Starting >>> opennav_coverage
Starting >>> opennav_coverage_bt
Finished <<< opennav_coverage_bt [0.18s]                                                                 
--- stderr: opennav_coverage                         
CMake Error at /opt/ros/humble/lib/x86_64-linux-gnu/cmake/absl/abslTargets.cmake:1909 (message):
  The imported target "absl::log_severity" references the file

     "/opt/ros/humble/lib/lib/libabsl_log_severity.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/opt/ros/humble/lib/x86_64-linux-gnu/cmake/absl/abslTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /opt/ros/humble/lib/x86_64-linux-gnu/cmake/absl/abslConfig.cmake:32 (include)
  /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/ros/humble/lib/x86_64-linux-gnu/cmake/ortools/ortoolsConfig.cmake:33 (find_dependency)
  /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/ros/humble/lib/cmake/fields2cover/Fields2CoverConfig.cmake:14 (find_dependency)
  CMakeLists.txt:18 (find_package)


---
Failed   <<< opennav_coverage [1.29s, exited with code 1]
                                
Summary: 3 packages finished [3.45s]
  1 package failed: opennav_coverage
  1 package had stderr output: opennav_coverage
  3 packages not processed

```

**Debug**
1. Checked the file libabsl_log_severity.a via find /opt/ros/humble -name "libabsl_log_severity.a" and I see it exists

**Request**:
Could you please help resolve this issue

**Comment by SteveMacenski** [comment]
I have never seen this error in all my years in ROS... so I really can't say, seems like not related to thsi project through given how low into cmake it goes. Your best bet is to google around or ask on Robotics Stack Exchange and hope someone's had a similar experience. I'd recommend cleaning your system and rebuilding from scratch after a full update and see if that resolves the issue. 

Hope that helps! Sorry this isn't a heres-your-answer response, this seems related to your system setup rather than this package in particular. This package seems to be just what triggers it.

**Comment by pl3703** [comment]
I believe this failure is very easy to reproduce. Here are my steps
1. Install a brand new Ubuntu 22.04
2. Install ros2 iron
3. Install navigation2
4. Install fields2cover using `sudo apt install ros-iron-fields2cover`
5. Clone this opennav_coverage repo
6. Then build it using `colon build`, the error of libabsl_log_severity.a missing is there

**Comment by pl3703** [comment]
> I have never seen this error in all my years in ROS... so I really can't say, seems like not related to thsi project through given how low into cmake it goes. Your best bet is to google around or ask on Robotics Stack Exchange and hope someone's had a similar experience. I'd recommend cleaning your system and rebuilding from scratch after a full update and see if that resolves the issue.
> 
> Hope that helps! Sorry this isn't a heres-your-answer response, this seems related to your system setup rather than this package in particular. This package seems to be just what triggers it.

Hi @SteveMacenski , the error comes from ros-iron-fields2cover installed by apt, could you take a  second look? Thanks!

**Comment by SteveMacenski** [comment]
I'm not the maintainer on fields2cover, you should file a ticket with that project!

**Comment by pl3703** [comment]
Noted, thanks for the quick reply!
