### ISSUE TITLE
help with implimenting opennav_coverage

### ISSUE THREAD

**Issue by yash7321** [open-navigation/opennav_coverage#80]
system details:ubuntu 22.04,ros2 Jazzy Jalisco,
nav2 and Fields2Cover are installed

tThe error occurs because the behaviortree_cpp headers from multiple versions (e.g., behaviortree_cpp and behaviortree_cpp_v3) are conflicting. 

if i remove (sudo apt remove ros-jazzy-behaviortree-cpp) , i am unable to fing nav2_core when installing, then i install nav2 with (sudo apt install ros-jazzy-nav2-core) it is also installing behaviortree_cpp ,which again is cousing conflit, 

how do i resolve this.

if my approch is wrong please guide me on how to use this in my project
![Screenshot from 2024-11-15 18-32-48](https://github.com/user-attachments/assets/95382850-4517-4831-b51e-301980193bde)
![Screenshot from 2024-11-15 18-36-35](https://github.com/user-attachments/assets/5d2f4963-539d-4f2b-a1cd-4386cdfcc206)
![Screenshot from 2024-11-15 18-42-30](https://github.com/user-attachments/assets/e1e7e692-37b5-4f0b-b94c-048b25b2c62d)

**Comment by Ragnar7982** [comment]
Hello @yash7321 , Did u fix it? I can't build it with humble as well
